services:
  - type: web
    name: nmap-scan-backend
    plan: free
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
    domains:
      - backend.yourdomain.com # Replace with your actual domain

  - type: web
    name: nmap-scan-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    envVars:
      - key: NODE_ENV
        value: production
    domains:
      - frontend.yourdomain.com # Replace with your actual domain
