services:
  - type: web
    name: nmap-scan-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: nmap-scan-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    envVars:
      - key: NODE_ENV
        value: production
